spring:
  datasource:
    url: jdbc:h2:mem:hr_db
    driverClassName: org.h2.Driver
    username: admin
    password: 123456!A
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

server:
  port: 8282
